INSERT INTO tb_category(name, created_At) VALUES('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Smartphones', NOW());
INSERT INTO tb_category(name, created_At) VALUES('TV and Video', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Audio', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Camera', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Drones', NOW());
INSERT INTO tb_category(name, created_At) VALUES('PC gamer', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Security', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Home appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Small appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Musical instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Music', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Movies', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Market', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Pet', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Bag', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Sportweare', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Clock', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Sustainability', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Healthcare', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Perfumery', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Religion', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Courses', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Bed', NOW());
INSERT INTO tb_category(name, created_At) VALUES('Virtual card', NOW());